# Generated by Django 5.0.6 on 2024-08-03 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='entry_no',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
