# Generated by Django 5.0.6 on 2024-08-03 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0003_alter_studentdetails_entry_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='challan_no',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='entry_no',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
